# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(282, 267)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.label.setObjectName("label")
        self.id_input = QtWidgets.QLineEdit(self.centralwidget)
        self.id_input.setGeometry(QtCore.QRect(42, 10, 231, 22))
        self.id_input.setObjectName("id_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 41, 21))
        self.label_2.setObjectName("label_2")
        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(52, 40, 221, 22))
        self.name_input.setObjectName("name_input")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 111, 21))
        self.label_3.setObjectName("label_3")
        self.degree_input = QtWidgets.QLineEdit(self.centralwidget)
        self.degree_input.setGeometry(QtCore.QRect(120, 70, 151, 22))
        self.degree_input.setObjectName("degree_input")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.label_4.setObjectName("label_4")
        self.type_input = QtWidgets.QLineEdit(self.centralwidget)
        self.type_input.setGeometry(QtCore.QRect(130, 100, 141, 22))
        self.type_input.setObjectName("type_input")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 111, 21))
        self.label_5.setObjectName("label_5")
        self.description_input = QtWidgets.QLineEdit(self.centralwidget)
        self.description_input.setGeometry(QtCore.QRect(110, 130, 161, 22))
        self.description_input.setObjectName("description_input")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 41, 21))
        self.label_6.setObjectName("label_6")
        self.price_input = QtWidgets.QLineEdit(self.centralwidget)
        self.price_input.setGeometry(QtCore.QRect(50, 160, 221, 22))
        self.price_input.setObjectName("price_input")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 111, 21))
        self.label_7.setObjectName("label_7")
        self.volume_input = QtWidgets.QLineEdit(self.centralwidget)
        self.volume_input.setGeometry(QtCore.QRect(120, 190, 151, 22))
        self.volume_input.setObjectName("volume_input")
        self.addButtonFromForm = QtWidgets.QPushButton(self.centralwidget)
        self.addButtonFromForm.setGeometry(QtCore.QRect(90, 230, 91, 24))
        self.addButtonFromForm.setObjectName("addButtonFromForm")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ID:"))
        self.label_2.setText(_translate("MainWindow", "Имя:"))
        self.label_3.setText(_translate("MainWindow", "Степень обжарки:"))
        self.label_4.setText(_translate("MainWindow", "Молотый/в зернах:"))
        self.label_5.setText(_translate("MainWindow", "Описание вкуса:"))
        self.label_6.setText(_translate("MainWindow", "Цена:"))
        self.label_7.setText(_translate("MainWindow", "Объем упаковки:"))
        self.addButtonFromForm.setText(_translate("MainWindow", "Добавить"))
